### ISSUE TITLE
Create a program to split the PDF files vertically

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#119]
The PDF files from Scanbox are double sided PDF files.
We have to split the manually.

Scantailor gives a good UI. But it does too many post processing and makes the text in PDF too bulky.

Write a GUI application to

1. Open a double sided PDF file
2. add a visual vertical line mark  as page splitter at center of the page automatically.
3. Check and change the Mark a visual page splitter for each page, if required
5. If split is not required, delete the visual mark. (Few pages may already single)
5. Split them to individual pages

**Comment by tshrinivasan** [comment]
[சார்பியல் தத்துவம்.pdf](https://github.com/KaniyamFoundation/ProjectIdeas/files/5084496/default.pdf)

Here is a sample PDF.

This may be symmetrical. But many books may not be symmetrical.

**Comment by vanangamudi** [comment]
Here is the short demo[1] of the tool I am working. I thought of un-skewing  image using opencv but some pages have V or inverted-V shaped gap between them. So I just went ahead with making this tool. UI part is almost done as you can see in the video. As you can see the video is old one. For the last couple days I want hunting down a stupid error. Now all the slicing images part of code is also done. 

Will share the code[2] as soon as the tool is done. 

[1] https://www.youtube.com/watch?v=HbDwBGSyOp8&feature=youtu.be
[2] https://github.com/vanangamudi/thaal-vetti/

**Comment by vanangamudi** [comment]
The code repo [1] is now public. Fixed few issues and I think the tool is usable now. 

[1] https://github.com/vanangamudi/thaal-vetti/

**Comment by vanangamudi** [comment]
Here is the latest demo[1] . I have tested couple of books, it seems to work well enough. Takes around 5 minutes on average for a book with around 100 pages. If you find any issues please raise an issue in the github repo. 

[1] https://www.youtube.com/watch?v=KPWtCIlqz3I&feature=youtu.be

**Comment by tshrinivasan** [comment]
Found a tool "Krop" which does the same visually quickly.

https://arminstraub.com/software/krop

**Comment by balajijagadesh** [comment]
I found briss very efficient. It has a visual version too. Briss2.0
