### ISSUE TITLE
நிகண்டியம் திட்டம் நிரல் 2 - Web Scraping

### ISSUE THREAD

**Issue by IngersolNorway** [KaniyamFoundation/ProjectIdeas#143]
**அனைவருக்கும் வணக்கம்**

நான் இங்கர்சால் நார்வேயில் இருந்து வள்ளுவர் வள்ளலார் வட்டம் என்ற குழுமத்தை ஒருங்கிணைத்து வருகிறேன், அதில் அகராதிகளை டிஜிட்டல் செய்யும் ''நிகண்டியம் திட்டம்'' பணி முனைப்பாக நடந்து கொண்டிருக்கிறது. இதுவரை பல லட்சம் சொற்களை தொகுத்து விட்டோம், அதில் பல ஆயிரம் சொற்கள் இதுவரை டிஜிட்டல் உலகின் உருவாக்கப்படாமல் உள்ள புதிய சொற்கள் ஆகும்.

எங்கள் டிஜிட்டல் பணியை எளிமை படுத்த சில நிரல் தேவைப்படுகிறது.

இணையதளத்தில் இருக்கும் ஆங்கில அகராதி சொற்கள் அதன் விளக்கங்களுடன் எடுத்து தர வேண்டும். உதாரணமாக சில தளங்களில் Index/Glossary பக்கங்கள் இருக்கிறது. ஒவ்வொரு சொல்லையும் சொடுக்கினால் அதற்கான விளக்கங்கள் வருகிறது. இதனை எக்சல் வடிவில் ஒரு சொல்லும் அதன் பொருளும் இருக்குமாறு Web Scraping சேகரித்து உருவாக்கித் தர வேண்டும்.

பொதுவாக அகராதிகளில் நவீன தொழில் நுட்ப சொற்கள் இருப்பதில்லை.  இவ்வாறு சொற்களை தொகுத்து சொல்லறிஞர்களை வைத்து தமிழ் சொல் உருவாக்க திட்டம்.  
நண்பர்கள் உதவவும்

**இங்கர்சால்
வள்ளுவர் வள்ளலார் வட்டம்**

**Comment by tshrinivasan** [comment]
எந்த தளத்தை scrap செய்ய வேண்டும்?

முழு விவரங்கள் தருக.

**Comment by IngersolNorway** [comment]
Hi @tshrinivasan

**WEBSITE1** 

https://www.gartner.com/en/glossary/all-terms

எக்ஸல் வடிவில்
சொல் ஒரு நெடுவரிசையிலும் 
பொருள் ஒரு நெடுவரிசையிலும் 
வேண்டும்

[New Technologies glossary.xlsx](https://github.com/KaniyamFoundation/ProjectIdeas/files/6000556/New.Technologies.glossary.xlsx)

**Comment by IngersolNorway** [comment]
Hi @tshrinivasan

**WEBSITE2**

https://shodhganga.inflibnet.ac.in/handle/10603/20927

இதில் 389 முனைவர் தலைப்புகள் உள்ளது. 
ஒவ்வொரு தலைப்பிலு பல PDF உள்ளது 
தலைப்புவாரியாக FOLDER அமைத்து அதில் அந்ததந்த PDF வேண்டும்

**Comment by selvamanisampath** [comment]
> 
> WEBSITE1
> 
> https://www.gartner.com/en/glossary/all-terms
> 
> எக்ஸல் வடிவில்
> சொல் ஒரு நெடுவரிசையிலும்
> பொருள் ஒரு நெடுவரிசையிலும்
> வேண்டும்

தங்களின் இந்த தேவை நிறைவு செய்யப்பட்டு விட்டது. இந்த [நிரலை](https://github.com/selvamanisampath/web_scraping) பயன்படுத்தி தங்களுக்குத் தேவையானவற்றை எக்ஸல் வடிவில் பெற்றுக் கொள்ளலாம். அதில் எவ்வாறு இயக்குவது என்பதற்கான வழிமுறையும் கொடுத்துள்ளேன். ஏதேனும் சந்தேகம் எனில் அழையுங்கள்.

**Comment by IngersolNorway** [comment]
செல்வமணி சம்பத் உங்களது உதவிக்கு மிக்க நன்றி 
இதனை எப்படி செய்வது என்பது எனக்கு தெரியாது 
முயற்சி செய்து பார்க்கிறேன் தடங்கல் ஏதாவது வந்தால் 
உங்கள் தொடர்புக்கு வருகிறேன் 
மீண்டும் மீண்டும் நன்றி 🙏

**Comment by selvamanisampath** [comment]
@IngersolNorway நிச்சயமாக !!!  தங்களுக்குத் தேவையான தரவு தயாராக உள்ளது. ஆனால் README ஆவணத்தை பின்பற்றினால் தாங்களே தரவை உருவாக்கிக் கொள்ள முடியும். உதவி வேண்டுமெனில் அழையுங்கள்.

**Comment by selvamanisampath** [comment]
`WEBSITE2

https://shodhganga.inflibnet.ac.in/handle/10603/20927

இதில் 389 முனைவர் தலைப்புகள் உள்ளது.
ஒவ்வொரு தலைப்பிலு பல PDF உள்ளது
தலைப்புவாரியாக FOLDER அமைத்து அதில் அந்ததந்த PDF வேண்டும்`

நான் இதை ஆராய்ந்து கொண்டிருக்கிறேன். கூடிய விரைவில் பதிலளிக்கிறேன்.

**Comment by IngersolNorway** [comment]
நன்றி செல்வமணி சம்பத்

**Comment by IngersolNorway** [comment]
இந்த தலத்தில் உள்ள சொற்களும் எக்செல் வடிவில் வேண்டும். நண்பர்கள் உதவவும் @selvamanisampath 

SCRAPPING 1

PAGES FROM
https://www.freetamilfont.com/english-to-tamil.php
TO
https://www.freetamilfont.com/english-to-tamil.php?pg=3445


SCRAPPING 2

PAGES FROM
https://www.freetamilfont.com/tamil-to-english.php
TO
https://www.freetamilfont.com/tamil-to-english-alpha.php?al=121&pg=5

NOTE THIS SCRAPPING 2 DESIGN IS DIFFERENT FROM 1
FOR EXAMPLE, அ HAS 99 SUB PAGES
https://www.freetamilfont.com/tamil-to-english-alpha.php?al=72&pg=1
https://www.freetamilfont.com/tamil-to-english-alpha.php?al=72&pg=99

**Comment by gopig494** [comment]
scraping of https://www.gartner.com/en/glossary/all-terms 

git link : https://github.com/gopig494/Python-Projects/blob/master/garter.com_website_scraping.py

blog link : https://gopilearnpython.wordpress.com/2021/06/16/web-scraping-ii-by-using-python/

fork and run the program on your pc you will get the data as csv file.

**Comment by IngersolNorway** [comment]
Thanks a lot Gopi
