### ISSUE TITLE
Tesseract கொண்டு பார்வை மாற்று திறனாளிகளுக்கான ஒரு ஆன்ட்ராய்டு OCR செயலி

### ISSUE THREAD

**Issue by khaleeljageer** [KaniyamFoundation/ProjectIdeas#153]

**Comment by khaleeljageer** [comment]
https://github.com/khaleeljageer/OCR-Tamil

இந்த repository-ல், இந்த செயலி உருவாக்கத்திற்கு தேவையான அடிப்படை  வசதிகளை எழுதியுள்ளேன். இதை கொண்டு செயலிக்கு முழு வடிவம் கொடுக்க வேண்டும்...

**Comment by manimaran96** [comment]
@khaleeljageer 
நானும் பங்களிக்கிறேன்

**Comment by manimaran96** [comment]
pdf load from local and convert to bitmap images 
need to improve. 

Commit : https://github.com/manimaran96/OCR-Tamil/commit/1e11e017a131b47307cab2c454fe8a5bd4450975 & https://github.com/khaleeljageer/OCR-Tamil/pull/1/commits/bc60f23fb13779cd23f1ae74ba2a1e516bd16986
PR : https://github.com/khaleeljageer/OCR-Tamil/pull/1

**Comment by khaleeljageer** [comment]
App published [here](https://play.google.com/store/apps/details?id=com.jskaleel.vizhi_tamil).
