### ISSUE TITLE
TRANSLITERATION - மலையாளத்தை தமிழில் எழுத வேண்டும்

### ISSUE THREAD

**Issue by IngersolNorway** [KaniyamFoundation/ProjectIdeas#155]
மலையாள சொல்லை தமிழில் எழுத தெரிந்தவர்கள் தொடர்புக்கு வரவும்.  

உதாரணமாக നിലവറ (nilavaṟa) = நிலவறா (Cellar)

கூகுள் TRANSLITERATIONனை பயன்படுத்தி (nilavaṟa) ஆங்கில உச்சரிப்பு செல்லை உருவாக்கிவிடலாம். அதைப் படித்து தமிழில் #நிலவறா எழுதினால் போதுமானது.

கணிப்பொறி நிரல் எழுதி, கூகுளை பயன்படுத்தி, இதனை தானியக்க தெரிந்த நண்பர்கள் உதவலாம்.

![179468826_4021863044518355_2438177691403018251_n](https://user-images.githubusercontent.com/79217639/116372954-30b2d680-a80d-11eb-95c9-6c964783d028.jpg)

**Comment by thirumurugan-git** [comment]
@IngersolNorway நான் எனது பங்களிப்பினை அளிக்கிறேன். EXISTING DICTIONARY எவ்வாறு சேமிக்கப்பட்டுள்ளது?. அதனுடைய புகைப்படம் அல்லது  மாதிரி தரவு (SAMPLE DATA) கிடைத்தால் மிகவும் நன்று. அதற்கு ஏற்றவாறு எனது நிரலை எழுதி தருகிறேன்.

**Comment by IngersolNorway** [comment]
@thirumurugan-git 
Thanks a lot Thiru. 
Someone already helped for this issue.

**Comment by tshrinivasan** [comment]
@IngersolNorway இதற்கு நிரல் எழுதப்பட்டதா ?

ஆம் எனில் நிரலை பகிர வேண்டுகிறேன்.

**Comment by IngersolNorway** [comment]
@tshrinivasan நீச்சல்காரன் உதவினார்.. அவரிடம் இருக்கலாம்.. தருவாரா என்று தெரியவில்லை
