### ISSUE TITLE
வலைத்தளத்திற்கான தமிழ் மொபைல் கீபோர்டு தளவமைப்பு 

### ISSUE THREAD

**Issue by IngersolNorway** [KaniyamFoundation/ProjectIdeas#157]
வலைத்தளத்திற்கான தமிழ் மொபைல் கீபோர்டு தளவமைப்பு
(TAMIL MOBILE KEYBOARD LAYOUT FOR WEBSITE)

கைப்பேசியில் தட்டச்சு செய்யும் அதே முறையை, வலைதளத்திலும் எழுதும் படி, அதே விசைப்பலகை இருக்கிறதா?

அல்லது உருவாக்க முடிந்தவர்கள் உதவவும்
![TAMIL KEYBOARD](https://user-images.githubusercontent.com/79217639/118954768-60fa1a80-b95e-11eb-8b3f-44f8aee812b2.png)

**Comment by tshrinivasan** [comment]
படத்தில் உள்ள விசைப்பலகை மொபைல் கருவிக்கானது.

இதை அப்படியே கணினிக்கு பயன்படுத்த இயலாது.

வலைதளங்களுக்கான தட்டச்சு கருவி இதோ - https://github.com/wikimedia/jquery.ime

Firefox/Chrome நீட்சியாகவும் கிடைக்கிறது.


   - Firefox extension
   <https://addons.mozilla.org/en-US/firefox/addon/wikimedia-input-tools/>
   - Chrome extension
   <https://chrome.google.com/webstore/detail/wikimedia-input-tools/fjnfifedbeeeibikgpggddmfbaeccaoh>

**Comment by tshrinivasan** [comment]
தமிழுக்கு உள்ள விசைப்பலகைகள் பட்டியல்
https://github.com/wikimedia/jquery.ime/tree/master/rules/ta

இது வி்க்கிப்பீடியாவில் பயன்படு்த்தப் படுகிறது.

**Comment by IngersolNorway** [comment]
Issue Closed

https://www.vilaiyaatu.com/eluttu/ta-keypad/

**Comment by IngersolNorway** [comment]
https://www.vilaiyaatu.com/eluttu/ta-keypad/

**Comment by tshrinivasan** [comment]
Please release the source code in any open license, so that others can use
and learn.
