### ISSUE TITLE
புத்தகங்கள் அனுமதி பெற பயணம்

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/ProjectIdeas#16]
அன்பூடையீர்

கிழ்கண்ட நூல் ஆசிரியர்களை சந்தித்து நூல்கள் அனுமதி மற்றும் கி.கா உரிமையை பற்றிய விழிப்புணர்வு மற்றும் கிண்டில் கருவி அறிமுகம் மேலும் பல பணிகளை மேற்கொள்ள கோயம்பூத்துர் செல்ல இருக்கிறேன்

1.http://kovaignani.org/downloadbooks/ 
இவரிடம்சில வருடங்களுக்கு முன்பு அலைபேசியில் பேசி இருக்கிறேன்.ஆர்வமாக உள்ளார். நேரில் விளக்கம் அளித்து அவரின் எழுத்துகளை fte பெறலாம்அவரின் 45 நூல்களை இணையத்தில் இருக்கிறது.

2.https://pamaran.wordpress.com/

பாமரனிடம் சில ஆண்டுகளுக்கு முன்பு பேசி உள்ளேன் நேரில் சென்றால் இசைவார்

3.எழுத்தாளர் ராஜேஷ்குமார்

நேரில் சந்தித்து கி.கா உரிமை கிண்டில் அறிமுகம் நாவல்கள் மின் நூல் அனுமதி கோரவேண்டும்

4.ஓசை செல்லா

நீண்ட நாள் நண்பர் இவற்றை ஒருங்கிணைக்கவும் கி.கா உரிமை மற்றும் மின் நூல் அனுமதி பெற வேண்டும்.

5.மொளனத்தின் சாட்ச்சியம் நாவல்
ஆசிரியர் சம்சுதீன் ஹீரா திருப்பூர் இவரிடம் பேசிவிட்டேன் நேரில் புத்தகத்தைம்ற்றும் கிகா உரிமை விளக்கம் கொடுக்க வேண்டும்.

கோவையில் மட்டும் 3 நாட்கள் கோவையில் தோராயமாக 2500 இருந்து 3000 எங்களது ஊரில் இருந்து போக போகிறேன்.

**Comment by gnuanwar** [comment]
Acknowledge in telegram

**Comment by tshrinivasan** [comment]
acknowledge here as this is public viewable place.

**Comment by KarkeeUdayan** [comment]
பயணம் சிறக்க வாழ்த்துகள்

**Comment by gnuanwar** [comment]
நன்றி

**Comment by tshrinivasan** [comment]
பயணம் இனிதே நிறைவு பெற்றது.
குறிப்புகள் இங்கே - http://www.kaniyam.com/event-notes-travel-to-covai-for-books/
