### ISSUE TITLE
Add tamil99 input method to emacs

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#186]
Emacs editor has inbuilt method layouts and selector.

```
M-x list-input methods 
```

can list the available methods.

Tamil99 is not there.

![image](https://user-images.githubusercontent.com/1268536/176335616-3b8f0c38-2de3-4bc4-91fb-03b5a797b93f.png)

Explore on how to add tamil99 there and add it.

**Comment by tshrinivasan** [comment]
https://www.reddit.com/r/emacs/comments/ffg77o/how_to_contribute_an_input_system_to_emacs/

@vanangamudi already started search for it.

**Comment by tshrinivasan** [comment]
related link - https://scripter.co/gujarati-transliteration/

**Comment by tshrinivasan** [comment]
related link - https://emacsnotes.wordpress.com/2022/03/07/tamil-phonetic-input-method-in-emacs-emacs-%e0%ae%87%e0%ae%b2%e0%af%8d-%e0%ae%a4%e0%ae%ae%e0%ae%bf%e0%ae%b4%e0%af%8d-%e0%ae%83%e0%ae%aa%e0%af%8a%e0%ae%a9%e0%af%86%e0%ae%9f%e0%ae%bf%e0%ae%95%e0%af%8d/

**Comment by arunisaac** [comment]
I have a complete and working tamil99 input method at https://git.systemreboot.net/tamil99/about/ It's also packaged for Guix. See https://guix.gnu.org/en/packages/emacs-tamil99-0.1.2/

Maybe, I'll try to get it accepted into emacs upstream. WDYT?

**Comment by arunisaac** [comment]
I just sent a patch adding the tamil99 input method to bug-gnu-emacs. See https://issues.guix.gnu.org/58070 Since Emacs maintainers are unlikely to know the Tamil language, it would be very helpful if someone here were to provide feedback and catch any shortcomings early. Thanks!

**Comment by arunisaac** [comment]
The tamil99 input method has now been added to the development version of Emacs. See https://issues.guix.gnu.org/58070#41 This issue may now be closed.

**Comment by tshrinivasan** [comment]
https://github.com/vizs/tamil99

Here also a solution.

**Comment by tshrinivasan** [comment]
Thanks @arunisaac for your code and pushing to upstream.
It works well.
