### ISSUE TITLE
Make the epub files Tidy

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#24]
We make epub files for FreeTamilebooks.com by using calibre's ebook-convert tool.

ebook-convert name.odt name.epub

This converts to epub.
when extracting the epub, it gives many HTML files.
The HTML content is too cluttered and has unwanted tags.

clean those unwanted html tags and make them tidy.

Need a python or command line tool to do below.

1. get epub as input
2. extract it
3. Open each html file and Tidy up it
4. rebuild as new epub file
5. validate the epub file with any epub validator

**Comment by Dineshkarthik** [comment]
Can we add a sample epub with those unwanted tags and list of some known unwanted tags here?

**Comment by tshrinivasan** [comment]
http://freetamilebooks.com/download/%e0%ae%ae%e0%ae%be%e0%ae%b0%e0%af%8d%e0%ae%95%e0%ae%b4%e0%ae%bf%e0%ae%a4%e0%af%8d-%e0%ae%a4%e0%ae%bf%e0%ae%99%e0%af%8d%e0%ae%95%e0%ae%b3%e0%af%8d-%e0%ae%ae%e0%ae%a4%e0%ae%bf-%e0%ae%a8%e0%ae%bf/

Download a sample epub from here

try validating with http://validator.idpf.org/ and https://www.ebookit.com/tools/bp/Bo/eBookIt/epub-validator

we covert a doc/docx/odt as epub.
libre office is adding too many tags on the HTML files.
We need to tidy them.
explore on auto tidying.

We need headings, bold, italic, images, tables only on the result files.
remove all other unwanted tags.
