### ISSUE TITLE
மின் நூல்களில் விக்கிபிடியா, திறந்த மூலங்களை இணைப்பது 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/ProjectIdeas#41]
பிரி தமிழ் இபுக்ஸ் நூல்களில் விக்கிபிடியா,osm தகவல்களை இனி வரும் புத்தகத்தின் content-ல் இணைக்கலாம்

**Comment by tshrinivasan** [comment]
We wont edit the books and add the links for wikipedia.
Authors should do this.

Hence, closing this issue.
