### ISSUE TITLE
Create a low cost custom scan box

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#73]
We need to create a low cost custom scan box, so that we can scan books easily.

the existing scanners are costly.

SV600 - 47,000 INR
https://www.amazon.in/Fujitsu-PA03641-B301-ScanSnap-SV600-Scanner/dp/B01AJI0426

CZUR ET 16 Plus Smart Book Scanner  - 56,000 INR
https://www.amazon.in/CZUR-Plus-Smart-Scanner-Black/dp/B0758VY4G7

Instead of this, make a scanbox like
https://www.kickstarter.com/projects/limemouse/scanbox-turn-your-smartphone-into-a-portable-scann

https://www.amazon.com/Scanner-Bin-Document-Scanning-Solution/dp/B00XM7LKZM

**Comment by tshrinivasan** [comment]
![photo6285311525753301252](https://user-images.githubusercontent.com/1268536/63986728-dbcc3380-caf2-11e9-8d99-d5f933bfb18f.jpg)

Created the above box.

Expenses so far - plywood, carpenter charge - 2100

Pending items
1. Making a 2.5 inch hole on the top
2. Painting inside and outside
3. Adding 4 LED lamps on inner side of TOP
4. Getting a thick non reflective glass to press the big books

**Comment by gnuanwar** [comment]
Srini check Kalyan recommendations 
[30/08, 7:42 AM] kalyan greenbooks: Design to be improved
[30/08, 7:45 AM] kalyan greenbooks: Lots of glare will be there in this design. Lights to be away from camera area. If you want I give you physical drawing. I think I have it. You may try with that.
[30/08, 9:08 AM] Gnuanwar: Ok give me the drawing we try tell me when I need to collect

**Comment by tshrinivasan** [comment]
http://techforelders.blogspot.com/2012/12/blog-post.html
Found here a good alternate.

Have to fit the lights on the side walls and fit white sheets in between.

**Comment by tshrinivasan** [comment]
![photo6294043739726915845](https://user-images.githubusercontent.com/1268536/64250501-e98b1a00-cf33-11e9-88bc-6c66b6028c66.jpg)

![photo6291738312951572658](https://user-images.githubusercontent.com/1268536/64250503-ea23b080-cf33-11e9-8439-7851adc2b250.jpg)

![photo6292026384998050130](https://user-images.githubusercontent.com/1268536/64250505-ea23b080-cf33-11e9-990d-43bd79ab3b03.jpg)

![photo6291738312951572656](https://user-images.githubusercontent.com/1268536/64250506-ea23b080-cf33-11e9-9873-7f4f77a4ae8d.jpg)

![photo6294053888734636333](https://user-images.githubusercontent.com/1268536/64250507-eabc4700-cf33-11e9-92dc-8720d72b359c.jpg)

![photo6294053888734636332](https://user-images.githubusercontent.com/1268536/64250509-eabc4700-cf33-11e9-8edd-ef226cb23cae.jpg)

![photo6294053888734636331](https://user-images.githubusercontent.com/1268536/64250510-eabc4700-cf33-11e9-85b6-0a6fa13dc6cd.jpg)

**Comment by tshrinivasan** [comment]
Exploring on adding a semi transparent sheets between the lights and the glass to emit limited light.

Trying with sheets used in Drums.
https://images-na.ssl-images-amazon.com/images/I/81pDhddAfkL._SL1500_.jpg

**Comment by tshrinivasan** [comment]
![photo6307632247452313978](https://user-images.githubusercontent.com/1268536/64410288-57585280-d0a8-11e9-8736-5d4ea28ce161.jpg)
![photo6309903662381639852](https://user-images.githubusercontent.com/1268536/64410290-57585280-d0a8-11e9-8366-678ec7ae8472.jpg)
![photo6307632247452313979](https://user-images.githubusercontent.com/1268536/64410291-57f0e900-d0a8-11e9-931e-11e033471c1c.jpg)

**Comment by tshrinivasan** [comment]
Finally, added the thick mica sheet used on the drums to minimize the light reflection.

The box is ready to use now.

**Comment by tshrinivasan** [comment]
[தாமோதரம்.pdf](https://github.com/KaniyamFoundation/ProjectIdeas/files/3582805/1.pdf)

Here is sample scan from android phone with cam scanner.

Did post processing the scanned images using scantailor.
here is the result from scantailor
[thamodaram.pdf](https://github.com/KaniyamFoundation/ProjectIdeas/files/3582808/thamodaram.pdf)

Found that tesseract 4 is good for Tamil OCR.
Here is the result.
[thamodaram.txt](https://github.com/KaniyamFoundation/ProjectIdeas/files/3582811/thamodaram.txt)

**Comment by tshrinivasan** [comment]
**Install Scantailor and tesseract**

> sudo apt-get install tesseract-ocr yagf tesseract-ocr-tam tesseract-ocr-script-taml tesseract-ocr python3-pyocr ocrodjvu ocrmypdf lios gimagereader
> 
> sudo apt-get install scantailor

1. scan a book
2. save as images
3. split, improve using scantailor

**split a pdf to multiple images using ghostscript**
gs -dNOPAUSE -dBATCH -sDEVICE=png16m -sOutputFile="Pic-%02d.png" output.pdf

**Do ocr using tesseract**

> ls -1Nv *.png > filelist.txt
> 
> tesseract -l eng+tam filelist.txt article txt

**Comment by tshrinivasan** [comment]
if the output from scanning is only double sided PDF, we can split it using mutool.

> mutool poster -x 2 input.pdf output.pdf

To crop the PDF, we can use pdfshuffler

![image](https://user-images.githubusercontent.com/1268536/64410806-76a3af80-d0a9-11e9-858b-f9131f45822f.png)

**Comment by tshrinivasan** [comment]
Here is a video on how to use scantailor

https://vimeo.com/12524529

**Comment by venkatarangan** [comment]
@tshrinivasan Thanks for the post, the scanner box is super impressive. 

I am interested in the software process. One problem which has been plaguing scanning of old Tamil books to PDF has been, the inability to select, copy n paste intelligible Tamil text (Unicode) from the PDF pages to say MS Word or Notepad. For this to work, I guessed we need to have an OCR to generate Tamil text somewhere in the pipeline and then embed the text back to the PDF. 

In this context, recently I found all the books in [Singapore's NLB Tamil collection](http://eresources.nlb.gov.sg/printheritage/browse/Tamil_Digital_Heritage_Collection.aspx), supporting seamless (extremely low error) copy n paste of Tamil text out from PDF. I have been researching how they are doing - I experimented with a python script to use Google Vision OCR to get something working after I saved all pages in a PDF as images. That's where I got stuck, unable to proceed further in the workflow.

Now, seeing [the tweet today](https://twitter.com/KaniyamMagazine/status/1170043199462629377),  I was pleasantly surprised, you have solved the problem. I have two queries:
1) In the [thamodharan.pdf ](https://github.com/KaniyamFoundation/ProjectIdeas/files/3582808/thamodaram.pdf) you generated from CamScanner->ScanTailor, the copy n paste of Tamil works. But you are mentioning you doing OCR with tesseract later. Am I missing something? If not, how is copy n paste working before OCR?

2) Once OCR is done, how to get the Tamil Unicode text back to the PDF. 

Lastly, can you write a detailed blog post on the steps outside this GitHub thread, as it will benefit a wider set of people (especially non-programmers) who wish to scan and support Copy N Paste for old Tamil books. 

Once again, many thanks for your effort and sharing them.

**Comment by tshrinivasan** [comment]
@venkatarangan The Tesseract OCR can give output as text file and PDF file.

PDF file is searchable. It adds a text layer ontop of the original image when producing the PDF output.

Will write detailed blog soon.

**Comment by tshrinivasan** [comment]
Initially, I thought that we do all the scan, fix images, improve images, convert to PDF using mobile itself.

Adobe scan, cam scanner kind of apps do this.

But, the results are not impressive.

Did a test with ScanTailor. It is the magician and King in this field.

Raw scan output

![Screenshot from 2019-09-08 20-31-07](https://user-images.githubusercontent.com/1268536/64490321-575b7c80-d279-11e9-8f85-d4b08189bc21.png)

Result from Adobe scan mobile app

![Screenshot from 2019-09-08 20-39-32](https://user-images.githubusercontent.com/1268536/64490328-65a99880-d279-11e9-9c9b-3147b4dab9b7.png)

See the difference of contrast across the page due to light reflection over the glass. They are not good for printing and OCRing.

But Found scantailor improves the image quality to a very high level.
It does all the magics to bring the super resulted images.

![Screenshot from 2019-09-08 20-34-06](https://user-images.githubusercontent.com/1268536/64490337-8f62bf80-d279-11e9-9358-66fe55d08517.png)

This is perfect for print or OCR.

**Comment by tshrinivasan** [comment]
Few inputs from bharat varma in twitter
https://twitter.com/BharatVarma3/status/1170241584031391744

Hinge glass at the far edge to ease book placement.

Cut panels on the side & put white acrylic sheets for light diffusion. Keep lights outside.

If using a camera, use a CPL filter to cut glare.

Use a long lens and an inclined base, and you can probably shoot two books at once.

---------------
you can add a CPL filter to a Point and shoot camera..
Point and shoots have three possibilities for attaching a CPL filter -

A filter thread on the lens itself, an add on accessory tube that attaches to the body with a threaded receptacle at the end & a similar small tube that can be stuck to the front of the tube housing the lens.

---------------



I
I                                O  < Camera  
|\\                 o
I  \\    o
I    \\
I___\\_______

Does this section work?  :)

The inclined lines are the base & the book.

"O" is camera with a long focal length (less distortion, edge to edge sharpness).

o o is direction.


The camera needs to be parallel to the book. Keeping it at a distance with a longer focal length makes it more forgiving of alignment issues and the minimal distortion ensures better quality images.

**Comment by nithyadurai87** [comment]
To convert all the tif output of scantailor to PDF

> ls *.tif | parallel convert {} {.}.pdf
> 
> pdfunite *.pdf bookname.pdf

**Comment by tshrinivasan** [comment]
Here is the first books scanned with this scanbox

https://archive.org/details/thamodharam

https://ia601401.us.archive.org/23/items/thamodharam/thamodharam.pdf

Camera used : Smart Phone Honor 9N

**Comment by venkatarangan** [comment]
@tshrinivasan Considering, the low-cost and OSS setup, the quality of the scan for this PDF is great. Kudos. If you are going to release this book (PDF) as such, I will request you add the tesseract OCR support as well so that the text becomes searchable.  Thanks.

**Comment by tshrinivasan** [comment]
@venkatarangan Sure sir, Dreaming of a website like FreeTamilEbooks.com but only with the scanned PDF files. 
Will launch the site soon.

Is it OK to go with the tesseract as there is a lot of room for improvement  for it with Tamil ?

**Comment by tshrinivasan** [comment]
Improved the scanbox.

Added a light at back side wall.

Now the results are more good.

**Comment by tshrinivasan** [comment]
![IMG_20191110_201408](https://user-images.githubusercontent.com/1268536/68546034-d0ea2500-03f8-11ea-8e24-1cc8bd1cc411.jpg)
![IMG_20191110_201241](https://user-images.githubusercontent.com/1268536/68546037-d8a9c980-03f8-11ea-8e7e-2cfd513e4c51.jpg)
![IMG_20191110_201135](https://user-images.githubusercontent.com/1268536/68546041-e1020480-03f8-11ea-9da2-5c3a12cabe3f.jpg)

**Comment by tshrinivasan** [comment]
Added a handle to the glass for easy operation.

**Comment by venkatarangan** [comment]
> **Install Scantailor and tesseract**
[Scan Tailor](https://scantailor.org/) is great. Thank you for referencing it here. I used it now to split pages (from two facing pages to single pages), straighten up the pages, despeckle (remove the non text/image areas like brown paper background) and then output clean sharp looking pages.

**Comment by gnuanwar** [comment]
Welcome

**Comment by tshrinivasan** [comment]
![image](https://user-images.githubusercontent.com/1268536/74214926-5960b600-4cc5-11ea-87a1-7192400d7ec4.png)


![image](https://user-images.githubusercontent.com/1268536/74214909-3f26d800-4cc5-11ea-9044-2514bbbfa6ce.png)

**Comment by tshrinivasan** [comment]
scanbox is now with Khaleel for scanning old magazines.

**Comment by tshrinivasan** [comment]
Wrote a blog post on making of scanbox
https://goinggnu.wordpress.com/2020/04/20/making-of-kaniyam-scanbox-diy-scanner/

More photos
https://photos.app.goo.gl/rCTpCaqkW8tZ68md9

**Comment by abubelinha** [comment]
Thank you guys. Amazing work 👍 👍 👍 
@abubelinha
