### ISSUE TITLE
Extract nouns from the sql of peyar.in

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#79]
peyar.in 

is a good website, which collects all good tamil names.

Here is the source code of the site
https://github.com/thamizha/peyar

attached the sql dump.
[peyar.sql.tar.gz](https://github.com/KaniyamFoundation/ProjectIdeas/files/3639274/peyar.sql.tar.gz)

parse it using text processing utilities and get all the names in a text file.
like ஆண்-அ.txt, ஆண்-ஆ.txt ஆண்-இ.txt  பெண்-அ.txt, பெண்-ஆ.txt, பெண்-இ.txt

so that we can add them in the huge noun list we are collecting for NLP projects.

**Comment by thamizhg** [comment]
[பெண்-அ.txt](https://github.com/KaniyamFoundation/ProjectIdeas/files/3655938/-.txt)

**Comment by tshrinivasan** [comment]
It is already done here
https://github.com/vanangamudi/tamil-name-gen/tree/master/old_stuff/data/tamil-names
