### ISSUE TITLE
Create google form to github issues integration

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/ProjectIdeas#86]
Create a google form to accept ebooks from authors.

add integration so that issues are created here automatically
https://github.com/KaniyamFoundation/Ebooks/issues

**Comment by sathia27** [comment]
@tshrinivasan How is this implemented right now?

I could see now we are using Firebox from below issues.
https://github.com/KaniyamFoundation/Ebooks/issues/277

Is this issue still open? How authors currently uploading e-books?

**Comment by tshrinivasan** [comment]
Created a form.

Working on connecting with github issue.
Facing some issues on getting data from submitted google form.

will fix soon.

**Comment by tshrinivasan** [comment]
https://forms.gle/4yHiS2uSgH5haTCW7

அவை தாமாகவே https://github.com/KaniyamFoundation/Ebooks/issues/ இங்கு
பகிரப்படும்.
