### ISSUE TITLE
Create python script  to run OCR using tesseract

### ISSUE THREAD

**Issue by Ananthsubray** [KaniyamFoundation/ProjectIdeas#94]
Tesseract OCR is currently giving a good output for the India languages. With the help of others, we are able to develop a [JS script](https://kn.wikisource.org/wiki/%E0%B2%B8%E0%B2%A6%E0%B2%B8%E0%B3%8D%E0%B2%AF:Ananth_subray/common.js) to OCR single page on Wiki. It will be good to have the python script to run OCR using the tesseract for bulk pages, something similar to OCR4Wikisource using Google OCR.

**Comment by arunlouie** [comment]
We have to split up implementation as specific modules. I see many features can be commonly used for other projects as well. 
My Suggestions is to have modules,
- Capability to load different file types
- Read as in words from the documents
- Curation - Make some auto correction 
- Maintain dictionary for curation
- etc

**Comment by balajijagadesh** [comment]
Wonderful suggestions

**Comment by rajeshkumargp** [comment]
Can we make use of these existing repos:
1) https://github.com/madmaze/pytesseract (Getting frequent Updates)
2) https://github.com/ratazzi/tesseract-ocr

@Ananthsubray and @tshrinivasan , Can you please elaborate the requirement

**Comment by tshrinivasan** [comment]
Here a linux version to OCR a given PDF file
https://gist.github.com/tshrinivasan/0aaf78e5808ee29490928614882cded0

Here is a windows GUI version
https://github.com/Parathantl/tesseract_gui/releases

Demo video in tamil - 
https://www.youtube.com/watch?v=363DGNL-rUw

Detailed notes are here
https://goinggnu.wordpress.com/2020/05/23/tesseract-ocr-gui-for-windows/

Thanks to  @Parathantl for the windows version.
